create database WORMHOLE;
create schema WORMHOLE.SCHEMA_MANAGEMENT;

create or replace TABLE WORMHOLE.SCHEMA_MANAGEMENT.CHANGE_HISTORY (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATABASE_NAME VARCHAR(50),
	SCHEMA_NAME VARCHAR(50),
	TABLE_NAME VARCHAR(50),
	OLD_COLUMN_NAME VARCHAR(50),
	OLD_DATA_TYPE VARCHAR(50),
	OLD_DATA_LENGTH NUMBER(38,0),
	NEW_COLUMN_NAME VARCHAR(50),
	NEW_DATA_TYPE VARCHAR(50),
	NEW_DATA_LENGTH NUMBER(38,0),
	CHANGE_TYPE VARCHAR(50),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key ("ID")
);


create or replace TABLE WORMHOLE.SCHEMA_MANAGEMENT.DDL_HISTORY (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATABASE_NAME VARCHAR(50),
	SCHEMA_NAME VARCHAR(50),
	TABLE_NAME VARCHAR(50),
	STATUS VARCHAR(50),
	CHANGES VARCHAR(16777216),
	DDL_STATEMENT VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);

create schema WORMHOLE.INGESTION;

create or replace table WORMHOLE.INGESTION.EMPLOYEES (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(20),
    LastName VARCHAR(20),
    Department VARCHAR(20),
    Position varchar(50),
    Salary INT
);

insert into INGESTION.EMPLOYEES 
(EmployeeID, FirstName, LastName, Department, Position, Salary)
values
(1, 'John', 'Doe', 'IT', 'Software Engineer', '80000'),
(2, 'Jane', 'Smith', 'HR', 'HR Manager', '90000'),
(3, 'Bob', 'Johnson', 'Finance', 'Accountant', '75000');

